### PR TITLE
style: add prettier

### PR DESCRIPTION
**Pull request by benediktms**
style: add prettier ignore file
style: apply formatting
style: install and apply svelte prettier

Adding as part of conversation from: https://github.com/ParthJadhav/Verve/issues/3#issuecomment-1379994571

Note: Probably it is also a good idea to add CI workflows to ensure linting is in the correct format

### CODE REVIEW

**Review by ParthJadhav — APPROVED** [review]
It looks so much cleaner now 🙌

Thanks for amazing changes @benediktms !!

**Comment by ParthJadhav** [comment]
Oh btw we can add lint command in package.json right? 
@benediktms

**Comment by benediktms** [comment]
@ParthJadhav Yes, my bad forgot to add that. I'll add one for `lint` and one for `format` 👍 speaking of which, at some point it probably also makes sesne sot use eslint for UI linting and clippt lint for rust linting

**Comment by ParthJadhav** [comment]
Awesome !! We'll merge that. Thanks for the Contribution @benediktms

**Pull request merged**
